[project]
name = "cmcdict"
description = "Python library to work with the CMC operational dictionary"
authors = ["Sebastien Fortier <sebastien.fortier@ec.gc.ca>"]
channels = ["conda-forge", "fortiers", "nodefaults"]
platforms = ["linux-64"]


[tasks.test]
description = "Run package tests"
cmd = "pytest -vrf"


[tasks.lint]
description = "Run lint on package"
cmd = "ruff check cmcdict"


[tasks.lint-fix]
description = "Run lint-fix on package"
cmd = "ruff check --fix cmcdict"

[tasks.format]
description = "Run format on package"
cmd = "ruff format -v ."

[tasks.build]
description = "Build package"
cmd = "python -m pip install -e ."

[tasks.doc]
description = "Make docs"
cmd = "cd docs && make doc"

[tasks.get-version]
description = "Check version"
cmd = "python -c \"import cmcdict; print(cmcdict.__version__)\""

[tasks.conda-build]
cmd = "rm -rf /tmp/conda-build && rattler-build build --recipe-dir conda.recipe --output-dir /tmp/conda-build -c fortiers -c conda-forge"

[tasks.render]
cmd = "conda-smithy rerender"

[tasks.conda-upload]
cmd = "rattler-build upload anaconda -v -o fortiers /tmp/conda-build/noarch/cmcdict-*.conda"
depends-on = ["conda-build"]

[dependencies]
python = "==3.10.12"
polars = ">=0.18.8"


[feature.dev.dependencies]
ipython = "==8.14.0"
myst-parser = "==1.0.0"
nbsphinx = "==0.9.2"
pygments = "==2.12.0"
pytest = "==7.4.0"
ruff = ">=0.0.280"
setuptools = "==58.5.3"
sphinx = "==5.3.0"
sphinx_rtd_theme = "==0.5.1"
sphinx-autodoc-typehints = "==1.21.8"
wheel = "*"
hatchling = "*"

[environments]
dev = ["dev"]

[target.linux-64.dependencies] 
