[project]
name = "cmcdict-tests"
description = "Test environments for cmcdict"
authors = ["Sebastien Fortier <sebastien.fortier@ec.gc.ca>"]
channels = ["conda-forge", "fortiers", "nodefaults"]
platforms = ["linux-64"]


[tasks]
tests = "cp -r ../../test . && cd test && pytest -vrf && cd .. && rm -rf test"

[dependencies]


[feature.py38.dependencies]
python = ">=3.8.0,<3.9"
cmcdict = { channel = "fortiers", version = ">=2025.3.0" }
pytest = "*"

[feature.py39.dependencies]
python = ">=3.9.0,<3.10"
cmcdict = { channel = "fortiers", version = ">=2025.3.0" }
pytest = "*"

[feature.py310.dependencies]
python = ">=3.10.0,<3.11"
cmcdict = { channel = "fortiers", version = ">=2025.3.0" }
pytest = "*"

[feature.py311.dependencies]
python = ">=3.11.0,<3.12"
cmcdict = { channel = "fortiers", version = ">=2025.3.0" }
pytest = "*"

[feature.py312.dependencies]
python = ">=3.12.0,<3.13"
cmcdict = { channel = "fortiers", version = ">=2025.3.0" }
pytest = "*"

[feature.py313.dependencies]
python = ">=3.8.0,<3.9"
cmcdict = { channel = "fortiers", version = ">=2025.3.0" }
pytest = "*"


[environments]
py38 = ["py38"]
py39 = ["py39"]
py310 = ["py310"]
py311 = ["py311"]
py312 = ["py312"]
py313 = ["py313"]
 