{% set name = load_setup_py_data()['name'] %}
{% set version = load_setup_py_data()['version'] %}
{% set url = load_setup_py_data()['url'] %}
{% set summary = load_setup_py_data()['description'] %}

package:
  name: {{ name|lower }}
  version: {{ version }}


build:
  number: 0
  noarch: python

requirements:
  build:
    - python

  run:
    - python


test:
  imports:
    - {{ name|lower }}

about:
  home: {{ url }}
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE
  summary: {{ summary }}

source:
  path: ../

