schema_version: 1

package:
  name: cmcdict
  version: "2025.3.0"

source:
  path: ../.

build:
  # Increment build number when you need to rebuild the package without changing its version.
  # For example, when:
  # - Updating dependencies without changing package functionality
  # - Fixing packaging issues (missing files, etc.)
  # - Making build process changes
  # Reset to 0 when you update the version number.
  number: 2
  noarch: python
  script:
    - python -m hatchling build
    - python -m pip install dist/*.whl


requirements:
  host:
    - python
    - pip
    - wheel
    - hatchling
  run:
    - python
    - polars >=0.18.8

tests:
  - python:
      imports:
        - cmcdict
      pip_check: false  # this is the default

  - script:
      - ls
    files:
      source:
        - data/*.xml


about:
  license: LGPL-3.0-or-later
  summary: Python library to work with the CMC operational dictionary
  homepage: https://gitlab.science.gc.ca/CMDS/cmcdict

extra:
  channels:
    - fortiers
    - conda-forge
    - nodefaults
  channel_priority: flexible  
